/**
 * Русская локализация интерфейса Plyr (подсказки, aria-label, меню настроек).
 * @see https://github.com/sampotts/plyr#internationalization-i18n
 */
export const plyrRuI18n = {
  restart: "С начала",
  rewind: "Назад на {seektime} с",
  play: "Воспроизвести",
  pause: "Пауза",
  fastForward: "Вперёд на {seektime} с",
  seek: "Перемотка",
  seekLabel: "{currentTime} из {duration}",
  played: "Воспроизведено",
  buffered: "Буфер",
  currentTime: "Текущее время",
  duration: "Длительность",
  volume: "Громкость",
  mute: "Без звука",
  unmute: "Включить звук",
  enableCaptions: "Включить субтитры",
  disableCaptions: "Выключить субтитры",
  download: "Скачать",
  enterFullscreen: "Полный экран",
  exitFullscreen: "Выйти из полного экрана",
  frameTitle: "Плеер: {title}",
  captions: "Субтитры",
  settings: "Настройки",
  pip: "Картинка в картинке",
  menuBack: "Назад",
  speed: "Скорость",
  normal: "Обычная",
  quality: "Качество",
  loop: "Повтор",
  start: "Начало",
  end: "Конец",
  all: "Все",
  reset: "Сброс",
  disabled: "Выкл.",
  enabled: "Вкл.",
  advertisement: "Реклама",
  qualityBadge: {
    2160: "4K",
    1440: "HD",
    1080: "HD",
    720: "HD",
    576: "SD",
    480: "SD",
  },
};
